# Generic testing workflow for PRs
# Created on 2025.03.20

name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branches:
        description: 'Comma-separated list of branches to run on'
        required: false
        default: 'main'
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.11'
      runner-label:
        description: 'Self-hosted runner label'
        required: false
        default: 'ubuntu-latest'
      test-path:
        description: 'Path to the tests directory'
        required: false
        default: 'tests/'
      coverage-module:
        description: 'Module to generate coverage for'
        required: false
        default: 'src'

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ github.event.inputs.runner-label || 'ubuntu-latest' }}

    env:
      PYTHON_VERSION: ${{ github.event.inputs.python-version || '3.11' }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MODEL_REGISTRY_HOST: ${{ secrets.MODEL_REGISTRY_HOST }}
      USERNAME: ${{ secrets.MODEL_REGISTRY_USERNAME }}
      PASSWORD: ${{ secrets.MODEL_REGISTRY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv sync --dev

      - name: Run tests
        run: >
          uv run pytest
          --cov=${{ github.event.inputs.coverage-module || 'src' }}
          --cov-report=xml
          --tb=line
          --doctest-modules
          ${{ github.event.inputs.test-path || 'tests/' }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: tests
          verbose: true
